### PR TITLE
Fix clan join logs

### LINKED ISSUE #756: Clan join log adds context incorrectly
Results in null values in ingame log message

### PR DESCRIPTION
**Pull request by StudentAlleg**
Fix how clan join logs apply context, allowing them to display logs correctly

Fixes #756

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

### CODE REVIEW

File: champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java [hunk 1]
```diff
@@ -146,6 +148,7 @@ public void invalidatePlayer(Player player, Gamer gamer) {
 
     @Override
     public void trackPlayer(Player player, Gamer gamer) {
+        log.info("equiped flash");
```
Comment (Mykindos) [inline champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java:151]: uh oh

**Review by Mykindos — CHANGES_REQUESTED** [review]

File: champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java [hunk 2]
```diff
@@ -33,6 +34,7 @@
 
 @Singleton
 @BPvPListener
+@Slf4j
```
Comment (StudentAlleg) [inline champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java:37]:
```suggestion
```

File: champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
 import com.google.inject.Inject;
 import com.google.inject.Singleton;
+import lombok.extern.slf4j.Slf4j;
```
Comment (StudentAlleg) [inline champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/axe/Flash.java:5]:
```suggestion
```
