### PR TITLE
Fix Title Flickering

### LINKED ISSUE #861: Title flickers when teleporting and fishing
There is fighting between the fishing title and the clan home title.
https://discord.com/channels/161738857136521217/1248459691646779413/1248459691646779413

### PR DESCRIPTION
**Pull request by StudentAlleg**
Fix Title flickering on c home. 

Now flickers if cancels (needs fixing)

Move Delayed Action to title queue

Fixes #861

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

### CODE REVIEW

**Comment by StudentAlleg** [comment]
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@31535778
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@31535778), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322)]
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@31535778
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe)]
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe)]
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 9 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a)]
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a)]
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a)]
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a)]
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:27] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:28] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a)]
[23:45:28] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:28] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:28] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:28] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a)]
[23:45:28] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@469982a3
[23:45:28] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300
[23:45:28] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:28] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:28] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6745632a
[23:45:28] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.moel.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300`

**Comment by StudentAlleg** [comment]
Looks like PriorityQueue add is not thread safe. An item is added with a higher priority than a current element, but is put at the end of the list (meaning it will be the displayed one), even though it should not be being displayed.
[partiallog.txt](https://github.com/user-attachments/files/15815286/partiallog.txt)

**Comment by StudentAlleg** [comment]
well I solved the ordering issue, but it now always flashes. Doesnt switch between things though.

**Comment by StudentAlleg** [comment]
It's a tomorrow problem

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java [hunk 1]
```diff
@@ -176,7 +176,7 @@ public void onClanHomeTeleport(ClanHomeTeleportEvent event) {
         });
 
         if (event.getDelayInSeconds() > 0) {
-            UtilMessage.simpleMessage(player, "Clans", "Teleporting to clan home in <green>%d</green> seconds, don't move!", event.getDelayInSeconds());
+            UtilMessage.simpleMessage(player, "Clans", "Teleporting to clan home in <green>%s</green> seconds, don't move!", event.getDelayInSeconds());
```
Comment (Mykindos) [inline clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java:179]: Make it %.1f

**Review by Mykindos — CHANGES_REQUESTED** [review]

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java (hunk 1 above)
Comment (StudentAlleg) [reply clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java]: done

**Comment by StudentAlleg** [comment]
@Mykindos want you to look over this and the structure before porting this to other queues. This system should be more thread safe, and explicitly define what to do if there are 2 or more elements with the same priority in the queue (uses the one added more recently).

**Review by Mykindos — APPROVED** [review]
