### PR TITLE
Fix Fissure breaking lily pads and pitcher plants

### LINKED ISSUE #1234: Fissure can break lilypads and pitcher plants at fields
https://discord.com/channels/161738857136521217/1305402814817636472

### PR DESCRIPTION
**Pull request by StudentAlleg**
Change how fissure stores blockdata (now correctly stores blockdata)

Change RestoreBlock to handle this functionality
Make RestoreBlock handle lily pads much better

Fixes #1234

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

### CODE REVIEW

File: core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java [hunk 1]
```diff
@@ -55,16 +63,22 @@ public void addRestoreBlock(@Nullable LivingEntity entity, Block block, Material
...
+                restoreBlock.setNewMaterial(newMaterial);
+                block.setType(newMaterial);
+            }
         } else {
-            RestoreBlock newRestoreBlock = new RestoreBlock(block, newMaterial, expiry, entity, label);
+            if (block.getType().equals(Material.WATER) && !newMaterial.equals(Material.WATER)) {
+                Block aboveBlock = block.getLocation().clone().add(0, 1, 0).getBlock();
+                if (aboveBlock.getType().equals(Material.LILY_PAD)) {
+                    addRestoreBlock(entity, aboveBlock, Material.AIR, expiry, force, label);
+                }
```
Comment (Mykindos) [inline core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java:75]: Instead of this specific case, I think you can do this (from my research)

if(!aboveBlock.getType().isSolid()) {
   addRestoreBlock(entity, aboveBlock, Material.AIR, expiry, force, label);
}

**Review by Mykindos — CHANGES_REQUESTED** [review]

File: core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java (hunk 1 above)
Comment (StudentAlleg) [reply core/src/main/java/me/mykindos/betterpvp/core/world/blocks/WorldBlockHandler.java]: done

**Review by Mykindos — APPROVED** [review]
