### PR TITLE
Fix clan sethome errors in the database

### LINKED ISSUE #695: Home column in table clans can be too short for home data
[20:11:41 ERROR]: [me.mykindos.betterpvp.core.logging.appenders.LegacyAppender] Error executing update: UPDATE clans SET Home = ? WHERE id = ?;
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'Home' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-j-8.2.0.jar:8.2.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912) ~[mysql-connector-j-8.2.0.jar:8.2.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054) ~[mysql-connector-j-8.2.0.jar:8.2.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003) ~[mysql-connector-j-8.2.0.jar:8.2.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312) ~[mysql-connector-j-8.2.0.jar:8.2.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988) ~[mysql-connector-j-8.2.0.jar:8.2.0]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[core.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[core.jar:?]
        at me.mykindos.betterpvp.core.database.Database.executeUpdate(Database.java:67) ~[core.jar:?]
        at me.mykindos.betterpvp.core.database.Database.lambda$executeUpdateAsync$0(Database.java:51) ~[core.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-451]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-451]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### PR DESCRIPTION
**Pull request by StudentAlleg**
Fixes data truncation erros, by explicitly using the datatypes that make up a location in the database

Fixes #695

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

### CODE REVIEW

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/repository/ClanRepository.java [hunk 1]
```diff
@@ -72,11 +71,20 @@ public List<Clan> getAll() {
...
-                Location home = UtilWorld.stringToLocation(result.getString(3));
-                boolean admin = result.getBoolean(4);
-                boolean safe = result.getBoolean(5);
-                String banner = result.getString(6);
-                final String vault = result.getString(7);
+                String homeWorld = result.getString(3);
+                double homeX = result.getDouble(4);
+                double homeY = result.getDouble(5);
+                double homeZ = result.getDouble(6);
+
```
Comment (StudentAlleg) [inline clans/src/main/java/me/mykindos/betterpvp/clans/clans/repository/ClanRepository.java:78]:
```suggestion
```
