### PR TITLE
Fix Clan Home existing in unclaimed territory

### LINKED ISSUE #773: Unclaiming territory with a clan home does not remove the clan home
Clan home is still able to be teleported to, even if it is no longer in claimed territory

### PR DESCRIPTION
**Pull request by StudentAlleg**
If the chunk with the clanhome is unclaimed, sets the home to null and alerts the clan

Fixes #773

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

### CODE REVIEW

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java [hunk 1]
```diff
@@ -128,6 +128,11 @@ public void onChunkUnclaim(ChunkUnclaimEvent event) {
         clanManager.getRepository().deleteClanTerritory(targetClan, chunkString);
         targetClan.getTerritory().removeIf(territory -> territory.getChunk().equals(UtilWorld.chunkToFile(chunk)));
 
+        if (targetClan.getHome().getChunk().equals(chunk)) {
+            targetClan.setHome(null);
```
Comment (Mykindos) [inline clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java:132]: You'l want to do this one too


            Block block = clan.getHome().clone().subtract(0, 0.6, 0).getBlock();
            if (block.getType() == Material.RED_BED) {
                block.setType(Material.AIR);
            }

**Review by Mykindos — CHANGES_REQUESTED** [review]

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java (hunk 1 above)
Comment (StudentAlleg) [reply clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java:132]: good point

Comment (StudentAlleg) [reply clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClanEventListener.java:136]: fixed
