### PR TITLE
Fix combat logging not giving dominance

### LINKED ISSUE #1089: Combat sheep does not give warpoints

### PR DESCRIPTION
**Pull request by StudentAlleg**
Fix combat logging not giving dominance when clicking the sheep

Fix combat log logic being incorrect

Fixes #1089 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

### CODE REVIEW

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansDeathListener.java [hunk 1]
```diff
@@ -58,6 +62,20 @@ public void onDeath(CustomDeathEvent event) {
...
     }
 
+    @EventHandler(priority = EventPriority.HIGH)
+    public void onSheepClick(PlayerClickCombatLogEvent event) {
+        UUID killer = event.getPlayer().getUniqueId();
+        UUID victim = event.getCombatLog().getOwner();
+        Clan killedClan = clanManager.getClanByPlayer(victim).orElse(null);
+        Clan killerClan = clanManager.getClanByPlayer(killer).orElse(null);
+
+        UtilServer.callEvent(new ClanAddExperienceEvent(Bukkit.getPlayer(killer), 0.1));
```
Comment (Mykindos) [inline clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansDeathListener.java:72]: Can just do event.getPlayer() ?

**Review by Mykindos — CHANGES_REQUESTED** [review]

File: clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansDeathListener.java (hunk 1 above)
Comment (StudentAlleg) [reply clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansDeathListener.java]: that's a good point, changed
